### ISSUE TITLE
To-do List

### ISSUE THREAD

**Issue by poojaswami16** [LetsBuildRockets/Horizon-Tracker#1]
- [x] test compass (magnetometer)
- [x] test code on raspberry pi (test with video on raspberry pi)
- [x] test camera on raspberry pi
- [x] set up software on both raspberry pi's (1)
  - [x] install opencv
  - [x] install node
- [x] set up software on both raspberry pi's (2)
  - [x] install opencv
  - [x] install node
- [x] automatically create new data folder for each new run
- [x] test how blurry the motion blur is
- [x] design and build a power supply
- [x] finish writing horizon tracker documentation
- [x] adjust vision algorithm to work with the camera
- [x] check compass values and make sure they're accurate
- [ ] figure out a way for the two pi's to communicate 
- [ ] assemble into payload tube
